### ISSUE TITLE
Boost colonial range

### ISSUE THREAD

**Issue by michaelranaldo** [Cousjava/EU4-HardColonialism#4]
With Bartholomew Diaz able to discover the Capein 1488, it should easily be possible to /explore/ far further than presently allowed. What should be limited is the range at which the Motherland is able to exhibit strong control over the colonies.

Colonies further from home ports (i.e. cores) should be increasingly frahile - while you could easily discover Indonesia by 1520, you shouldn't be able to colonise it til far later when your network has caught up

**Comment by Cousjava** [comment]
Maybe boost trade range as well, so European nations can put trade ships in the Indian Ocean by that time, but taking land from the natives will come much later.
